name: KarmicReport

main: com.mitsugaru.KarmicReport.KarmicReport

version: 0.01

website: http://dev.bukkit.org/server-mods/karmicreport/

description: User report and comment system, to keep a history of infractions

authors:
  - Mitsugaru

softdepend: [Vault, KarmicJail]

commands:
  report:
    description: Root command for KarmicShare
    usage: /report ? - Show help on KarmicShare

permissions:
    KarmicReport.*:
        description: Gives access to all KarmicShare commands
        children:
            KarmicReport.view: true
            KarmicReport.edit: true
            KarmicReport.warp: true
            KarmicReport.admin: true
        default: op
    KarmicReport.view:
        description: Allows user view another user's report
        default: op
    KarmicReport.edit:
        description: Allows user edit a report
        default: op
    KarmicReport.warp:
        description: Allows user to warp to location attached to report
        default: op
    KarmicReport.admin:
        description: Allows administration of plugin
        default: op